### ISSUE TITLE
@ng-util/monaco how to register like monaco?

### ISSUE THREAD

**Issue by devcui** [ng-util/ng-util#58]
```ts
monaco.languages.register({id: "sql"})
 monaco.languages.setMonarchTokensProvider("sql", language as any)
```

**Comment by devcui** [comment]
like this ?
```ts
 onEditorEvent(event: NuMonacoEditorEvent): void {
    const {editor} = event
    switch (event.type) {
      case "init":
        monaco.languages.register({id: 'sql'});
        monaco.languages.setLanguageConfiguration('sql', conf);
        monaco.languages.setMonarchTokensProvider('sql', language);
        break;
      default:
        break;
    }
  }
```

**Comment by cipchk** [comment]
Pls refer to [Configure JSON Defaults](https://github.com/ng-util/ng-util/blob/master/packages/monaco-editor/README.md#configure-json-defaults).

**Comment by devcui** [comment]
Write in forRoot like static code, Can the current mode enable the http request to return code prompt fragments and register them in language?

**Comment by devcui** [comment]
like this https://github.com/devcui/ng-monaco/tree/master/src/app/routes/editor

**Comment by cipchk** [comment]
I think what you need, how to use `NU_MONACO_EDITOR_CONFIG` dependency injection into your EditorService, pls refer to https://angular.io/guide/dependency-injection-providers

**Comment by devcui** [comment]
oh~ good,  i forget that config can be modified by injection, thanks
