### ISSUE TITLE
Error @ng-util/markdown Unhandled Promise rejection: Cannot read properties of undefined (reading 'cdn')

### ISSUE THREAD

**Issue by santiarcgonz** [ng-util/ng-util#74]
Hello everyone

Currently I am getting the following error in version 14.0.1 of the library, before this error it worked normally.

Is there any way to fix it?

<img width="594" alt="image" src="https://github.com/ng-util/ng-util/assets/105655443/785eb645-6cec-4ed1-8e66-e3a1f984f04c">

Thank you so much.

**Comment by cipchk** [comment]
You can modify the [libs](https://github.com/ng-util/ng-util/blob/master/packages/markdown/markdown.config.ts#L13) parameter to change the cdn link or local path (Via`scripts` in `angular.json`).

**Comment by santiarcgonz** [comment]
> You can modify the [libs](https://github.com/ng-util/ng-util/blob/master/packages/markdown/markdown.config.ts#L13) parameter to change the cdn link or local path (Via`scripts` in `angular.json`).

Hi @cipchk , Can you give me an example of what I should put in angular.json Or do you know if the cdn is corrupt?

<img width="641" alt="image" src="https://github.com/ng-util/ng-util/assets/105655443/0f1f4c07-66f2-4009-ba6e-5297630e00f4">


The error continues after the modification that I show. Thank you for you help

**Comment by b-mi** [comment]
I hacked this library (after hours of suffering) by this code:

```    NuMarkdownModule.forRoot({ 
      libs: [
        'https://cdn.jsdelivr.net/npm/vditor@3.8.10/dist/index.min.js',
        'https://cdn.jsdelivr.net/npm/vditor@3.8.10/dist/index.css'
      ]
    })
```
